### ISSUE TITLE
Diagrams as images

### ISSUE THREAD

**Issue by arbimo** [emmanuel-pastor/chat-system#1]
Could the diagrams be exported as images ? (so I can have a look at them)

**Comment by emmanuel-pastor** [comment]
Oui, désolé, je vais le faire dès que possible dans l aprem. On a pas fait le diagramme de classe pour le moment, mais on compte l avoir fini pour demain.

**Comment by emmanuel-pastor** [comment]
J'ai exporté les diagrammes que l'on a fait en png. Il nous manque un diagramme de séquence au minimum et le diagramme de classe que nous tâcherons de finir pour demain.
